-- TẠO BẢNG MIỀN
CREATE TABLE MIEN(
	MAMIEN CHAR(1) NOT NULL PRIMARY KEY,
	CONSTRAINT MAMIN CHECK(MAMIEN IN ('B', 'T', 'N')),
	TENMIEN VARCHAR(30) UNIQUE
);


-- TẠO BẢNG NƯỚC
CREATE TABLE NUOC(
	MANUOC CHAR(3) NOT NULL PRIMARY KEY,
	TENNUOC VARCHAR(30) NOT NULL UNIQUE,
	THUDO VARCHAR(50) NOT NULL
);


-- TẠO BẢNG TỈNH
CREATE TABLE TINH(
	MATINH CHAR(2) NOT NULL,
	TENTINH VARCHAR(30) NOT NULL UNIQUE,
	DIENTICH FLOAT,
	CONSTRAINT DIENTICH CHECK (DIENTICH > 0),
	DANSO INT,
	CONSTRAINT DANSO CHECK (DANSO > 0),
	THIXA VARCHAR(50),
	MAMIEN CHAR(1) FOREIGN KEY REFERENCES MIEN(MAMIEN) NOT NULL,
	PRIMARY KEY (MATINH),
	CONSTRAINT MAMIEN CHECK(MAMIEN IN ('B', 'T', 'N'))
);


-- TẠO BẢNG BIÊN GIỚI
CREATE TABLE BIENGIOI(
	MATINH CHAR(2) FOREIGN KEY REFERENCES TINH(MATINH) NOT NULL,
	MANUOC CHAR(3) FOREIGN KEY REFERENCES NUOC(MANUOC) NOT NULL	
);


-- TẠO BẢNG LÁNG GIỀNG
CREATE TABLE LANGGIENG(
	MATINH CHAR(2) FOREIGN KEY REFERENCES TINH(MATINH) NOT NULL,
	LG CHAR(2) FOREIGN KEY REFERENCES TINH(MATINH) NOT NULL,
	CHECK (LG <> MATINH)
);

