CREATE TABLE KHACHHANG (
	MAKH VARCHAR(5) PRIMARY KEY NOT NULL,
	TENKHACHHANG VARCHAR(30) NOT NULL,
	DIACHI VARCHAR(50) NOT NULL,
	DT VARCHAR(11),
	CONSTRAINT CHECK_DT CHECK (DT LIKE '[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]'
							   OR DT LIKE '[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]'
							   OR DT LIKE '[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]'
							   OR DT LIKE '[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]'),
	EMAIL VARCHAR(30)
);

CREATE TABLE VATTU(
	MAVT VARCHAR(5) PRIMARY KEY,
	TENVT VARCHAR(30) NOT NULL,
	DVT VARCHAR(20) NOT NULL,
	GIAMUA MONEY NOT NULL,
	CHECK(GIAMUA > 0),
	SLTON INT NOT NULL,
	CHECK(SLTON >= 0)
);

CREATE TABLE HOADON(
	MAHD VARCHAR(10) PRIMARY KEY,
	NGAY SMALLDATETIME NOT NULL,
	CHECK(NGAY < GETDATE()),
	MAKH VARCHAR(5) NOT NULL,
	TONGTG FLOAT
);

CREATE TABLE CHITIETHOADON (
	MAHD VARCHAR(10) NOT NULL,
	MAVT VARCHAR(5) NOT NULL,
	SL INT,
	CONSTRAINT CHECK_SL CHECK(SL > 0),
	KHUYENMAI FLOAT,
	GIABAN FLOAT
);