-- 4.01. Tính tổng học bổng các khoa theo mẩu sau: MAKH, TONGHOCBONG.
SELECT MAKH, SUM(HOCBONG) AS TONGHOCBONG FROM SINHVIEN GROUP BY MAKH;

-- 4.02. Tính tổng học bổng các khoa theo mẩu sau: MAKH, TENKH, TONGHOCBONG.
SELECT K.MAKHOA, K.TENKHOA, SUM(HOCBONG) AS TONGHOCBONG
FROM SINHVIEN AS S, KHOA AS K
WHERE S.MAKH = K.MAKHOA
GROUP BY K.MAKHOA, K.TENKHOA;

-- 4.03. Cho biết điểm trung bình của các sinh viên theo mẫu sau: MASV, DIEMTB.
SELECT MASV, AVG(DIEM) AS DIEMTRUNGBINH
FROM KETQUA
GROUP BY MASV;

-- 4.04. Cho biết điểm trung bình của các sinh viên theo mẫu sau: MASV, HOSV, TENSV, DIEMTB.
SELECT S.MASV, S.HOSV, S.TENSV, AVG(K.DIEM) AS DIEMTRUNGBINH
FROM SINHVIEN AS S, KETQUA AS K
WHERE S.MASV = K.MASV
GROUP BY S.MASV, S.HOSV, S.TENSV;

-- 4.05. Cho biết điểm trung bình của các sinh viên học khoa tin học theo mẫu sau: MASV, HOSV, TENSV, DIEMTB.
SELECT S.MASV, S.HOSV, S.TENSV, AVG(K.DIEM) AS DIEMTRUNGBINH
FROM SINHVIEN AS S, KETQUA AS K
WHERE S.MASV = K.MASV
	AND S.MAKH = 'TH'
GROUP BY S.MASV, S.HOSV, S.TENSV;

-- 4.06. Cho biết điểm trung bình của các sinh viên có điểm trung bình lớn hơn hay bằng 5 theo mẫu
-- sau: MASV, HOSV, TENSV, DIEMTB.
SELECT S.MASV, S.HOSV, S.TENSV, AVG(K.DIEM) AS DIEMTRUNGBINH
FROM SINHVIEN AS S, KETQUA AS K
WHERE S.MASV = K.MASV
GROUP BY S.MASV, S.HOSV, S.TENSV
HAVING AVG(K.DIEM) >= 5;

-- 4.07. Cho biết điểm trung bình của các sinh viên học khoa tin học và có điểm trung bình lớn hơn
-- hay bằng 5 theo mẫu sau: MASV, HOSV, TENSV, DIEMTB.
SELECT S.MASV, S.HOSV, S.TENSV, AVG(K.DIEM) AS DIEMTRUNGBINH
FROM SINHVIEN AS S, KETQUA AS K
WHERE S.MASV = K.MASV
	AND S.MAKH = 'TH'
GROUP BY S.MASV, S.HOSV, S.TENSV
HAVING AVG(K.DIEM) >= 5;

-- 4.08. Tìm học bổng lớn nhất, học bổng trung bình, học bổng nhở nhất của các sinh viên học khoa
-- tin học. Chú ý chỉ xét các học bổng lớn hơn 0.
SELECT MAX(K.DIEM) AS DIEMLONNHAN, 
		AVG(K.DIEM) AS DIEMTRUNGBINH, 
		MIN(NULLIF(K.DIEM, 0)) AS DIEMNHONHAT
FROM SINHVIEN AS S, KETQUA AS K
WHERE S.MASV = K.MASV
	AND S.MAKH = 'TH';

-- 4.09. Tính điểm lớn nhất và nhỏ nhất của sinh viên.
SELECT MAX(K.DIEM) AS DIEMLONNHAN,
		MIN(NULLIF(K.DIEM, 0)) AS DIEMNHONHAT
FROM SINHVIEN AS S, KETQUA AS K
WHERE S.MASV = K.MASV;

-- 4.10. Tính điểm lớn nhất và nhỏ nhất của sinh viên học khoa tin học.
SELECT MAX(K.DIEM) AS DIEMLONNHAN,
		MIN(NULLIF(K.DIEM, 0)) AS DIEMNHONHAT
FROM SINHVIEN AS S, KETQUA AS K
WHERE S.MASV = K.MASV
	AND S.MAKH = 'TH';

-- 4.11. Cho biết kết quả đậu rớt theo mẫu sau: MASV, DIEMTB, KETQUA. KETQUA là ĐẬU nếu
-- DIEMTB >=5 và không có môn nào dưới 3, Ngược lại là RỚT.
SELECT S.MASV, AVG(K.DIEM) AS DIEMTRUNGBINH,
		CASE WHEN K.DIEM >= 5 THEN  'Đậu' ELSE 'Rớt' END AS KETQUA
FROM KETQUA AS K,  SINHVIEN AS S
WHERE S.MASV = K.MASV
GROUP BY S.MASV
ORDER BY S.MASV; -- ERRORS --

-- 4.12. Tìm điểm lớn nhất của sinh viên có mã số A01 theo mẫu sau: MAMH, TENMH, DIEM.
SELECT M.MAMH, M.TENMH, K.DIEM
FROM KETQUA AS K,  SINHVIEN AS S, MONHOC AS M,
	(SELECT MAX(DIEM) AS DIEM FROM KETQUA WHERE MASV = 'A01') AS TMP
WHERE S.MASV = K.MASV
	AND K.MAMH = M.MAMH
	AND S.MASV = 'A01'
	AND K.DIEM = TMP.DIEM;
;
-- 4.13. Đếm số sinh viên đi thi môn học theo mẫu sau: MAMH, TENMH, SOSV dự thi.
SELECT M.MAMH, M.TENMH, COUNT(K.MASV) AS SOSINHVIEN
FROM KETQUA AS K, MONHOC AS M
WHERE K.MAMH = M.MAMH
GROUP BY M.MAMH, M.TENMH;

-- 4.14. Đếm số môn thi của các sinh viên theo mẫu sau: MASV, HOSV, TENSV, Tổng số môn thi.
SELECT S.MASV, S.HOSV, S.TENSV, COUNT(K.MAMH) AS TONGSOMONTHI
FROM SINHVIEN AS S, KETQUA AS K
WHERE S.MASV = K.MASV
GROUP BY S.MASV, S.HOSV, S.TENSV;

-- 4.15. Cho biết tổng số sinh viên và học bổng của các khoa theo mẫu: MAKH, TENKH, Tổng sinh
-- viên, Tổng học bổng.
SELECT K.MAKHOA, K.TENKHOA, COUNT(S.MASV) AS TONGSINHVIEN, SUM(S.HOCBONG)
FROM SINHVIEN AS S, KHOA AS K
WHERE S.MAKH = K.MAKHOA
GROUP BY K.MAKHOA, K.TENKHOA;

-- 4.16. Cho biết tổng số sinh viên theo từng khoa có trong trường với mẫu sau: MAKH, TENKH, Số
-- sinh viên trong khoa.
SELECT KHOA.MAKHOA, KHOA.TENKHOA, COUNT(SINHVIEN.MASV) AS TONGSINHVIEN
FROM SINHVIEN RIGHT JOIN KHOA
ON SINHVIEN.MAKH = KHOA.MAKHOA
GROUP BY KHOA.MAKHOA, KHOA.TENKHOA;

-- 4.17. Thống kê kết quả thi trong các khoa theo mẫu sau: MAKH, TENKHOA, Số sinh viên trong
-- khoa, Số sinh viên đạt, Số sinh viên rớt.
SELECT KHOA.MAKHOA, KHOA.TENKHOA, COUNT(TMP.MASV) AS SOSINHVIEN,
	COUNT(CASE WHEN TMP.TB >= 5 THEN 'Đậu' END) AS SVDAU,
	COUNT(CASE WHEN TMP.TB < 5 THEN 'Rớt' END) AS SVROT
FROM KHOA LEFT JOIN 
	(SELECT S.MASV, S.MAKH, AVG(K.DIEM) AS TB
	FROM SINHVIEN AS S, KETQUA AS K
	WHERE S.MASV = K.MASV
	GROUP BY S.MASV, S.MAKH) AS TMP
ON KHOA.MAKHOA = TMP.MAKH
GROUP BY KHOA.MAKHOA, KHOA.TENKHOA;

-- 4.18. Thống kê kết quả thi trong các khoa chỉ các sinh viên nam theo mẫu sau: MAKH,
-- TENKHOA, Số sinh viên trong khoa, Số sinh viên đạt, Số sinh viên rớt.
SELECT KHOA.MAKHOA, KHOA.TENKHOA, COUNT(TMP.MASV) AS SOSINHVIEN,
	COUNT(CASE WHEN TMP.TB >= 5 THEN 'Đậu' END) AS SVDAU,
	COUNT(CASE WHEN TMP.TB < 5 THEN 'Rớt' END) AS SVROT
FROM KHOA LEFT JOIN 
	(SELECT S.MASV, S.MAKH, S.NAM, AVG(K.DIEM) AS TB
	FROM SINHVIEN AS S, KETQUA AS K
	WHERE S.MASV = K.MASV
	GROUP BY S.MASV, S.MAKH,  S.NAM
	HAVING S.NAM = 1) AS TMP
ON KHOA.MAKHOA = TMP.MAKH
GROUP BY KHOA.MAKHOA, KHOA.TENKHOA;

-- 4.19. Thống kế theo mẫu MAKH, TENKH, Tổng số sinh viên nam, Tổng số sinh viên nữ, tổng sinh viên.
SELECT KHOA.MAKHOA, KHOA.TENKHOA, 
	COUNT(CASE WHEN SINHVIEN.NAM = 1 THEN 1 END) AS TONGSVNAM,
	COUNT(CASE WHEN SINHVIEN.NAM = 0 THEN 0 END) AS TONGSVNU,
	COUNT(SINHVIEN.MASV) AS TONGSV
FROM SINHVIEN RIGHT JOIN KHOA
ON SINHVIEN.MAKH = KHOA.MAKHOA
GROUP BY KHOA.MAKHOA, KHOA.TENKHOA;

-- 4.20. Thống kế theo mẫu MAKH, TENKH, Tổng số sinh viên nam, Tổng số sinh viên nữ, tổng sinh
-- viên trong khoa tin học và anh văn có học bổng.
SELECT KHOA.MAKHOA, KHOA.TENKHOA, 
	COUNT(CASE WHEN SINHVIEN.NAM = 1 THEN 1 END) AS TONGSVNAM,
	COUNT(CASE WHEN SINHVIEN.NAM = 0 THEN 0 END) AS TONGSVNU,
	COUNT(SINHVIEN.MASV) AS TONGSV
FROM SINHVIEN JOIN KHOA
ON SINHVIEN.MAKH = KHOA.MAKHOA
	AND KHOA.MAKHOA IN ('TH', 'AV')
	AND SINHVIEN.HOCBONG > 0
GROUP BY KHOA.MAKHOA, KHOA.TENKHOA;